language: node_js

cache:
  directories:
  - node_modules

node_js:
  - '7'

php:
  - '7.0'

services:
  - docker

before_install:
  # TIMEZONE options here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  - export TZ=PST8PDT
  - openssl aes-256-cbc -K $encrypted_d68f0083a6dc_key -iv $encrypted_d68f0083a6dc_iv
    -in travis-encrypt.tar.gz.enc -out travis-encrypt.tar.gz -d
  - tar -xzf travis-encrypt.tar.gz
  # Change PHP version
  - phpenv global 7.0

install:
  - composer self-update
  - composer install -d ./src/server --prefer-source --no-interaction

script:
  - npm run test
